import typography from './src/constants/styles/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,jsx,tsx,ts}'],
  theme: {
    extend: {
      colors: {
        base: {
          black: '#000000',
          white: '#FFFFFF',
        },
        error: {
          default: '#E33C3C',
          border: '#FFBFBF',
          background: '#FFDADA',
        },
        gray: {
          '03': '#D1D3D7',
          50: '#FAFAFA',
          100: '#F4F4F4',
          200: '#EEEEEE',
          300: '#E0E0E0',
          400: '#BCBCBC',
          500: '#9E9E9E',
          600: '#757575',
          700: '#616161',
          800: '#424242',
          900: '#222222',
        },
        orange: {
          50: '#FFEBD1',
          100: '#FFCA95',
          200: '#FFAE6E',
          300: '#FF9347',
          400: '#FF7F2B',
          500: '#FF6A00',
          600: '#EC5F00',
          700: '#D24F00',
          800: '#BD4100',
          900: '#3D1A0E',
          a100: '#FFD181',
          a200: '#FFBE36',
          a400: '#FF9B00',
          a700: '#FF7700',
        },
        green: {
          a100: '#97FFC4',
          a200: '#49DA87',
          a400: '#29C36C',
          a700: '#15AA56',
        },
        lightBlue: {
          50: '#E3F5FF',
          100: '#BAE1FF',
          200: '#8ECFFF',
          300: '#5FBAFD',
          400: '#3BA9FC',
          500: '#009AFA',
          600: '#008BEB',
          700: '#067AD9',
          800: '#0069C8',
          900: '#004BA9',
          a100: '#7FB4FF',
          a200: '#3C8DFF',
          a400: '#1E7DFF',
          a700: '#0866FF',
        },
        yellow: {
          a100: '#FFF4CD',
          a200: '#FFEDA7',
          a400: '#FFE975',
          a700: '#F5D41E',
        },
        blue: {
          50: '#EFF0FF',
          100: '#DEE0FF',
          200: '#B5BBFF',
          300: '#7482FF',
          400: '#283FFF',
          500: '#0915FF',
          600: '#000DE8',
          700: '#050ECE',
          800: '#0005B3',
          900: '#000485',
        },
        mint: {
          a100: '#88FFB0',
          a200: '#3CFF88',
          a400: '#00FF53',
          a700: '#03E060',
        },
      },
      scale: {
        'btn-pressed': '0.95',
      },
      fontSize: {
        'display1-regular': [
          typography['display1-regular'].fontSize,
          typography['display1-regular'].others,
        ],
        'display1-bold': [typography['display1-bold'].fontSize, typography['display1-bold'].others],
        'display2-regular': [
          typography['display2-regular'].fontSize,
          typography['display2-regular'].others,
        ],
        'display2-bold': [typography['display2-bold'].fontSize, typography['display2-bold'].others],
        'title1-regular': [
          typography['title1-regular'].fontSize,
          typography['title1-regular'].others,
        ],
        'title1-bold': [typography['title1-bold'].fontSize, typography['title1-bold'].others],
        'title2-regular': [
          typography['title2-regular'].fontSize,
          typography['title2-regular'].others,
        ],
        'title2-bold': [typography['title2-bold'].fontSize, typography['title2-bold'].others],
        'header-bold': [typography['header-bold'].fontSize, typography['header-bold'].others],
        'body1-regular': [typography['body1-regular'].fontSize, typography['body1-regular'].others],
        'body1-bold': [typography['body1-bold'].fontSize, typography['body1-bold'].others],
        'body2-regular': [typography['body2-regular'].fontSize, typography['body2-regular'].others],
        'body2-bold': [typography['body2-bold'].fontSize, typography['body2-bold'].others],
        'label1-regular': [
          typography['label1-regular'].fontSize,
          typography['label1-regular'].others,
        ],
        'label1-bold': [typography['label1-bold'].fontSize, typography['label1-bold'].others],
        'label2-regular': [
          typography['label2-regular'].fontSize,
          typography['label2-regular'].others,
        ],
        'label2-bold': [typography['label2-bold'].fontSize, typography['label2-bold'].others],
      },
    },
  },
  plugins: [],
  future: {
    hoverOnlyWhenSupported: true,
  },
  important: true,
};
